import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--epoch', type=int, default=150, help='epoch number')
parser.add_argument('--model_name', type=str, default="VMKNet", help='model name')
parser.add_argument('--lr', type=float, default=5e-5, help='learning rate')
parser.add_argument('--batchsize', type=int, default=2, help='training batch size')
parser.add_argument('--trainsize', type=int, default=256, help='training dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=100, help='every n epochs decay learning rate')
parser.add_argument('--start_epoch', type=int, default=100, help='epoch number')
parser.add_argument('--load_mit', type=str, default=r'pt_save_path or checkpoints path', help='train from checkpoints')
parser.add_argument('--edge_root', type=str, default='', help='the training edge images root')
parser.add_argument('--rgb_root', type=str, default='', help='the training rgb images root')
parser.add_argument('--fs_root', type=str, default='', help='the training focal_slice images root')
parser.add_argument('--gt_root', type=str, default='', help='the training gt images root')
parser.add_argument('--test_rgb_root', type=str, default='', help='the test rgb images root')
parser.add_argument('--test_fs_root', type=str, default='', help='the test fs images root')
parser.add_argument('--test_gt_root', type=str, default='', help='the test gt images root')
parser.add_argument('--save_path', type=str, default='', help='the path to save models and logs')
opt = parser.parse_args()